version: '3.6'
services:
  rpinvr:
    container_name: rpinvr
    hostname: rpinvr
    image: cyb3rdoc/rpinvr:latest
    volumes:
      - ./volumes/rpinvr/config:/app/config
      - ./volumes/rpinvr/storage:/app/storage
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    network_mode: "host"
